"""auto-generate-tables

Revision ID: cc613426af4d
Revises: c254a2f54d8e
Create Date: 2024-07-17 18:15:08.627500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc613426af4d'
down_revision: Union[str, None] = 'c254a2f54d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('author_Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('author_Id')
    )
    op.create_unique_constraint(None, 'borrowers', ['email'])
    op.add_column('ratings', sa.Column('upVote', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ratings', 'borrowers', ['borrower_id'], ['borrower_id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'ratings', 'books', ['book_id'], ['book_id'], ondelete='CASCADE')
    op.drop_column('ratings', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'upVote')
    op.drop_constraint(None, 'borrowers', type_='unique')
    op.drop_table('authors')
    # ### end Alembic commands ###
